### ISSUE TITLE
Add sample of syntax to documentation on how to configure an ant build.xml to run command using the ant sfdx jar.  

### ISSUE THREAD

**Issue by plbrownoptivcom** [mcartoixa/ant-sfdx#1]
Below is my first attempt at adding the retrieve command but haven't got it to working yet..

<force-mdapi-retrieve retrievetargetdir="force-app_sfdx" targetusername="paul@mydomain.sbxbld" unpackaged="manifest/package.xml">
</force-mdapi-retrieve>

**Comment by mcartoixa** [comment]
Thanks for your interest in this project. There does not seem to be much _below_ your question but I think I can give you an answer anyway 😉 

First of all I will reference you to the different documentations:

- obviously you will need to know how to use Ant: https://ant.apache.org/manual/index.html.
  - more specifically you will need to use the Taskdef task: https://ant.apache.org/manual/Tasks/taskdef.html.
- then there is a documentation for this project available here: https://mcartoixa.github.io/ant-sfdx/.

As for an example, the following is untested but it should work like this:
```xml
<project name="example" default="build" xmlns:sfdx="com.mcartoixa.ant.sfdx">
  <target name="build">
    <taskdef uri="com.mcartoixa.ant.sfdx" resource="com/mcartoixa/ant/sfdx/antlib.xml" classpath="ant-sfdx.jar" />
    <sfdx:force-org-list />
  </target>
</project>
```
